neg_tweets = [('I do not like this car', 'negative'),
              ('This view is horrible', 'negative'),
              ('I feel tired this morning', 'negative'),
              ('I am not looking forward to the concert', 'negative'),
              ('He is my enemy', 'negative'),
              ('Crust is not good.', 'negative'),
			  ('Not tasty and the texture was just nasty.', 'negative'),
			  ('Now I am getting angry and I want my damn pho.', 'negative'),
			  ('Honeslty it didnt taste THAT fresh.)', 'negative'),
			  ('The potatoes were like rubber and you could tell they had been made up ahead of time being kept under a warmer.', 'negative'),
			  ('Would not go back.', 'negative'),
			  ('The cashier had no care what so ever on what I had to say it still ended up being wayyy overpriced.', 'negative'),
			  ('I was disgusted because I was pretty sure that was human hair.', 'negative'),
			  ('I was shocked because no signs indicate cash only.', 'negative'),
			  ('Waitress was a little slow in service.', 'negative'),
			  ('This place is not worth your time, let alone Vegas.', 'negative'),
			  ('did not like at all.', 'negative'),
			  ('The Burrittos Blah', 'negative'),
			  ('- They never brought a salad we asked for.', 'negative'),
			  ('The worst was the salmon sashimi.', 'negative'),
			  ('This was like the final blow', 'negative'),
			  ('seems like a good quick place to grab a bite of some familiar pub food, but do yourself a favor and look elsewhere.', 'negative'),
			  ('Poor service, the waiter made me feel like I was stupid every time he came to the table.', 'negative'),
			  ('Service sucks.', 'negative'),
			  ('There is not a deal good enough that would drag me into that establishment again.', 'negative'),
			  ('Frozen pucks of disgust, with some of the worst people behind the register.', 'negative')]

# ('Its too bad the food is so damn generic.', 'negative'),
# 			  ('They have horrible attitudes towards customers, and talk down to each one when customers dont enjoy their food.', 'negative'),
# 			  ('The Heart Attack Grill in downtown Vegas is an absolutely flat-lined excuse for a restaurant.', 'negative'),
# 			  ('Not much seafood and like 5 strings of pasta at the bottom.', 'negative'),
# 			  ('The ripped banana was not only ripped, but petrified and tasteless.', 'negative'),
# 			  ('At least think to refill my water before I struggle to wave you over for 10 minutes.', 'negative'),
# 			  ('We got the food and apparently they have never heard of salt and the batter on the fish was chewy.', 'negative'),
# 			  ('The service was meh.', 'negative'),
# 			  ('It took over 30 min to get their milkshake, which was nothing more than chocolate milk.', 'negative'),
# 			  ('The scallop dish is quite appalling for value as well.', 'negative'),
# 			  ('2 times - Very Bad Customer Service ', 'negative'),
# 			  ('There is so much good food in Vegas that I feel cheated for wasting an eating opportunity by going to Rice and Company.', 'negative'),
# 			  ('walked in and the place smelled like an old grease trap and only 2 others there eating.', 'negative'),
# 			  ('The turkey and roast beef were bland.', 'negative'),
# 			  ('The pan cakes everyone are raving about taste like a sugary disaster tailored to the palate of a six year old.', 'negative'),
# 			  ('The poor batter to meat ratio made the chicken tenders very unsatisfying.', 'negative'),
# 			  ('In summary, this was a largely disappointing dining experience.', 'negative'),
# 			  ('Never been to Hard Rock Casino before, WILL NEVER EVER STEP FORWARD IN IT AGAIN', 'negative'),
# 			  ('say bye bye to your tip lady', 'negative'),
# 			  ('Well never go again.', 'negative'),
# 			  ('It was not good.', 'negative'),
# 			  ('REAL sushi lovers, lets be honest - Yama is not that good.', 'negative'),
# 			  ('At least 40min passed in between us ordering and the food arriving, and it wasnt that busy.', 'negative'),
# 			  ('It was pretty gross', 'negative'),
# 			  ('Ive had better atmosphere.', 'negative'),
# 			  ('Kind of hard to mess up a steak but they did.', 'negative'),
# 			  ('Although I very much liked the look and sound of this place, the actual experience was a bit disappointing.', 'negative'),
# 			  ('Worst service to boot, but that is the least of their worries.', 'negative'),
# 			  ('Host staff were, for lack of a better word, BITCHES', 'negative'),
# 			  ('I wouldnt return.', 'negative'),
# 			  ('This place is way too overpriced for mediocre food.', 'negative'),
# 			  ('The management is rude.', 'negative'),
# 			  ('He was extremely rude and really, there are so many other restaurants I would love to dine at during a weekend in Vegas.', 'negative'),
# 			  ('Dont do it', 'negative'),
# 			  ('The waiter wasnt helpful or friendly and rarely checked on us.', 'negative'),
# 			  ('My husband and I ate lunch here and were very disappointed with the food and service.', 'negative'),
# 			  ('And the red curry had so much bamboo shoots and wasnt very tasty to me.', 'negative'),
# 			  ('The menu is always changing, food quality is going down & service is extremely slow.', 'negative'),
# 			  ('The service was a little slow , considering that were served by 3 people servers so the food was coming in a slow pace.', 'negative'),
# 			  ('I give it 2 thumbs down ', 'negative'),
# 			  ('We watched our waiter pay a lot more attention to other tables and ignore us.', 'negative'),
# 			  ('We waited for forty five minutes in vain.', 'negative'),
# 			  ('Crostini that came with the salad was stale.', 'negative'),
# 			  ('Unfortunately, we must have hit the bakery on leftover day because everything we ordered was STALE.', 'negative'),
# 			  ('I came back today since they relocated and still not impressed.', 'negative'),
# 			  ('Avoid at all cost', 'negative'),
# 			  ('So dont go there if you are looking for good food...', 'negative'),
# 			  ('Ive never been treated so bad.', 'negative'),
# 			  ('We also ordered the spinach and avocado salad; the ingredients were sad and the dressing literally had zero taste.', 'negative'),
# 			  ('Perhaps I caught them on an off night judging by the other reviews, but Im not inspired to go back.', 'negative'),
# 			  ('The service here leaves a lot to be desired.', 'negative'),
# 			  ('We literally sat there for 20 minutes with no one asking to take our order.', 'negative'),
# 			  ('I also decided not to send it back because our waitress looked like she was on the verge of having a heart attack.', 'negative'),
# 			  ('I dressed up to be treated so rudely', 'negative'),
# 			  ('It was probably dirt.', 'negative'),
# 			  ('The food sucked, which we expected but it sucked more than we could have imagined.', 'negative'),
# 			  ('When my order arrived, one of the gyros was missing.', 'negative'),
# 			  ('Im not really sure how Joeys was voted best hot dog in the Valley by readers of Phoenix Magazine.', 'negative'),
# 			  ('The live music on Fridays totally blows.', 'negative'),
# 			  ('Ive never been more insulted or felt disrespected.', 'negative'),
# 			  ('The warm beer didnt help.', 'negative'),
# 			  ('Ive lived here since 1979 and this was the first time Ive stepped foot into this place.', 'negative'),
# 			  ('The WORST EXPERIENCE EVER.', 'negative'),
# 			  ('Must have been an off night at this place.', 'negative'),
# 			  ('For about 10 minutes, we were waiting for her salad when we realized that it wasnt coming any time soon.', 'negative'),
# 			  ('Wont go back.', 'negative'),
# 			  ('Soggy and not good.', 'negative'),
# 			  ('Which are small and not worth the price.', 'negative'),
# 			  ('The service was a bit lacking.', 'negative'),
# 			  ('Lobster Bisque, Bussell Sprouts, Risotto, Filet ALL needed salt and pepper..and of course there is none at the tables.', 'negative'),
# 			  ('Hopefully this bodes for them going out of business and someone who can cook can come in.', 'negative'),
# 			  ('It was either too cold, not enough flavor or just bad.', 'negative'),
# 			  ('As for the "mains," also uninspired.', 'negative'),
# 			  ('If the food isnt bad enough for you, then enjoy dealing with the worlds worst/annoying drunk people.', 'negative'),
# 			  ('Ordered a double cheeseburger & got a single patty that was falling apart (picture uploaded) Yeah, still sucks.', 'negative'),
# 			  ('If it were possible to give them zero stars, theyd have it.', 'negative'),
# 			  ('If she had not rolled the eyes we may have stayed... Not sure if we will go back and try it again.', 'negative'),
# 			  ('Horrible - dont waste your time and money.', 'negative'),
# 			  ('By this time our side of the restaurant was almost empty so there was no excuse.', 'negative'),
# 			  ('(It wasnt busy either) Also, the building was FREEZING cold.', 'negative'),
# 			  ('like the other reviewer said "you couldnt pay me to eat at this place again."', 'negative'),
# 			  ('-Drinks took close to 30 minutes to come out at one point.', 'negative'),
# 			  ('Based on the sub-par service I received and no effort to show their gratitude for my business I wont be going back.', 'negative'),
# 			  ('There is nothing privileged about working/eating there.', 'negative'),
# 			  ('I as well wouldve given godfathers zero stars if possible.', 'negative'),
# 			  ('very tough and very short on flavor', 'negative'),
# 			  ('I have been in more than a few bars in Vegas, and do not ever recall being charged for tap water.', 'negative'),
# 			  ('The service was not up to par, either.', 'negative'),
# 			  ('For a self proclaimed coffee cafe, I was wildly disappointed.', 'negative'),
# 			  ('Ive had better, not only from dedicated boba tea spots, but even from Jenni Pho.', 'negative'),
# 			  ('I think not again,' 'negative'),
# 			  ('I had the mac salad and it was pretty bland so I will not be getting that again.', 'negative'),
# 			  ('Service stinks here', 'negative'),
# 			  ('I waited and waited.', 'negative'),
# 			  ('This place is not quality sushi, it is not a quality restaurant.', 'negative'),
# 			  ('Things that went wrong: - They burned the saganaki.', 'negative'),
# 			  ('We waited an hour for what was a breakfast I could have done 100 times better at home.', 'negative'),
# 			  ('I hate to disagree with my fellow Yelpers, but my husband and I were so disappointed with this place.', 'negative'),
# 			  ('Waited 2 hours & never got either of our pizzas as many other around us who came in later did', 'negative'),
# 			  ('Just dont know why they were so slow.', 'negative'),
# 			  ('I live in the neighborhood so I am disappointed I wont be back here, because it is a convenient location.', 'negative'),
# 			  ('Never again will I be dining at this place', 'negative'),
# 			  ('Please stay away from the shrimp stir fried noodles.', 'negative'),
# 			  ('The potato chip order was sad... I could probably count how many chips were in that box and it was probably around 12.', 'negative'),
# 			  ('Food was really boring.', 'negative'),
# 			  ('This greedy corporation will NEVER see another dime from me', 'negative'),
# 			  ('Will never, ever go back.', 'negative'),
# 			  ('As much as Id like to go back, I cant get passed the atrocious service and will never return.', 'negative'),
# 			  ('She ordered a toasted English muffin that came out untoasted.', 'negative'),
# 			  ('Never going back.', 'negative'),
# 			  ('The bus boy on the other hand was so rude.', 'negative'),
# 			  ('The only downside is the service.', 'negative'),
# 			  ('Also, the fries are without a doubt the worst fries Ive ever had.', 'negative'),
# 			  ('I go to far too many places and Ive never seen any restaurant that serves a 1 egg breakfast, especially for $4.00.', 'negative'),
# 			  ('When my mom and I got home she immediately got sick and she only had a few bites of salad.', 'negative'),
# 			  ('The servers are not pleasant to deal with and they dont always honor Pizza Hut coupons.', 'negative'),
# 			  ('Everything was gross.', 'negative'),
# 			  ('First - the bathrooms at this location were dirty- Seat covers were not replenished & just plain yucky', 'negative'),
# 			  ('The burger... I got the "Gold Standard" a $17 burger and was kind of disappointed.', 'negative'),
# 			  ('There is nothing authentic about this place.', 'negative'),
# 			  ('the spaghetti is nothing special whatsoever.', 'negative'),
# 			  ('The selection was probably the worst Ive seen in Vegas.....there was none.', 'negative'),
# 			  ('We sat another ten minutes and finally gave up and left.', 'negative'),
# 			  ('He was terrible', 'negative'),
# 			  ('It shouldnt take 30 min for pancakes and eggs.', 'negative'),
# 			  ('Sadly, Gordon Ramseys Steak is a place we shall sharply avoid during our next trip to Vegas.', 'negative'),
# 			  ('The buffet is small and all the food they offered was BLAND.', 'negative'),
# 			  ('Definitely a turn off for me & i doubt Ill be back unless someone else is buying.', 'negative'),
# 			  ('I find wasting food to be despicable, but this just wasnt food.', 'negative'),
# 			  ('My wife had the Lobster Bisque soup which was lukewarm.', 'negative'),
# 			  ('I left with a stomach ache and felt sick the rest of the day.', 'negative'),
# 			  ('They dropped more than the ball.', 'negative'),
# 			  ('And the beans and rice were mediocre at best.', 'negative'),
# 			  ('I took back my money and got outta there.', 'negative'),
# 			  ('RUDE & INCONSIDERATE MANAGEMENT.', 'negative'),
# 			  ('I wont be back.', 'negative'),
# 			  ('The food was terrible.', 'negative'),
# 			  ('WILL NEVER EVER GO BACK AND HAVE TOLD MANY PEOPLE WHAT HAD HAPPENED.', 'negative'),
# 			  ('I dont recommend unless your car breaks down in front of it and you are starving.', 'negative'),
# 			  ('This place deserves one star and 90% has to do with the food.', 'negative'),
# 			  ('This is a disgrace.', 'negative'),
# 			  ('Im probably one of the few people to ever go to Ians and not like it.', 'negative'),
# 			  ('This one is simply a disappointment.', 'negative'),
# 			  ('Overall, I was very disappointed with the quality of food at Bouchon.', 'negative'),
# 			  ('I dont have to be an accountant to know Im getting screwed', 'negative'),
# 			  ('Left very frustrated.', 'negative'),
# 			  ('TOTAL WASTE OF TIME.', 'negative'),
# 			  ('For service, I give them no stars.', 'negative'),
# 			  ('I can take a little bad service but the food sucks.', 'negative'),
# 			  ('Gave up trying to eat any of the crust (teeth still sore).', 'negative'),
# 			  ('But now I was completely grossed out.', 'negative'),
# 			  ('Furthermore, you cant even find hours of operation on the website', 'negative'),
# 			  ('Weve tried to like this place but after 10+ times I think were done with them.', 'negative'),
# 			  ('What a mistake that was', 'negative'),
# 			  ('Waiter was a jerk.', 'negative'),
# 			  ('Strike 2, who wants to be rushed.', 'negative'),
# 			  ('I never come again.', 'negative'),
# 			  ('Ordered an appetizer and took 40 minutes and then the pizza another 10 minutes.', 'negative'),
# 			  ('It was a huge awkward 1.5lb piece of cow that was 3/4ths gristle and fat.', 'negative'),
# 			  ('Ill take my business dinner dollars elsewhere.', 'negative'),
# 			  ('Nothing special.', 'negative'),
# 			  ('Will not be back.', 'negative'),
# 			  ('Sauce was tasteless.', 'negative'),
# 			  ('I dont think well be going back anytime soon.', 'negative'),
# 			  ('I was so insulted.', 'negative'),
# 			  ('The last 3 times I had lunch here has been bad.', 'negative'),
# 			  ('The chicken wings contained the driest chicken meat I have ever eaten.', 'negative'),
# 			  ('Definitely not worth the $3 I paid.', 'negative'),
# 			  ('The manager was the worst.', 'negative'),
# 			  ('I dont think Ill be running back to Carlys anytime soon for food.', 'negative'),
# 			  ('The one down note is the ventilation could use some upgrading.', 'negative'),
# 			  ('Dont waste your time here.', 'negative'),
# 			  ('Total letdown, I would much rather just go to the Camelback Flower Shop and Cartel Coffee.', 'negative'),
# 			  ('Third, the cheese on my friends burger was cold.', 'negative'),
# 			  ('We asked for the bill to leave without eating and they didnt bring that either.', 'negative'),
# 			  ('Seafood was limited to boiled shrimp and crab legs but the crab legs definitely did not taste fresh.', 'negative'),
# 			  ('The selection of food was not the best.', 'negative'),
# 			  ('I dont think I will be back for a very long time.', 'negative'),
# 			  ('It was attached to a gas station, and that is rarely a good sign.', 'negative'),
# 			  ('Worse of all, he humiliated his worker right in front of me..Bunch of horrible name callings.', 'negative'),
# 			  ('And then tragedy struck.', 'negative'),
# 			  ('Id rather eat airline food, seriously.', 'negative'),
# 			  ('I would not recommend this place.', 'negative'),
# 			  ('Overall I wasnt very impressed with Noca.', 'negative'),
# 			  ('My gyro was basically lettuce only.', 'negative'),
# 			  ('Terrible service', 'negative'),
# 			  ('Thoroughly disappointed', 'negative'),
# 			  ('it was a drive to get there.', 'negative'),
# 			  ('Anyway, I do not think i will go back there.', 'negative'),
# 			  ('A greasy, unhealthy meal.', 'negative'),
# 			  ('first time there and might just be the last.', 'negative'),
# 			  ('Similarly, the delivery man did not say a word of apology when our food was 45 minutes late.', 'negative'),
# 			  ('And it was way to expensive.', 'negative'),
# 			  ('Terrible management.', 'negative'),
# 			  ('If there were zero stars I would give it zero stars.', 'negative'),
# 			  ('Worst martini ever', 'negative'),
# 			  ('We waited for thirty minutes to be seated (although there were 8 vacant tables and we were the only folks waiting).', 'negative'),
# 			  ('I wont try going back there even if its empty.', 'negative'),
# 			  ('No, Im going to eat the potato that I found some strangers hair in it.', 'negative'),
# 			  ('not even a "hello, we will be right with you."', 'negative'),
# 			  ('The desserts were a bit strange.', 'negative'),
# 			  ('I guess maybe we went on an off night but it was disgraceful.', 'negative'),
# 			  ('However, my recent experience at this particular location was not so good.', 'negative'),
# 			  ('I know this is not like the other restaurants at all, something is very off here', 'negative'),
# 			  ('AVOID THIS ESTABLISHMENT', 'negative'),
# 			  ('I think this restaurant suffers from not trying hard enough.', 'negative'),
# 			  ('My salad had a bland vinegrette on the baby greens and hearts of Palm.', 'negative'),
# 			  ('After two I felt disgusting.', 'negative'),
# 			  ('I will never go back to this place and will never ever recommended this place to anyone', 'negative'),
# 			  ('The servers went back and forth several times, not even so much as an "Are you being helped?"', 'negative'),
# 			  ('AN HOUR... seriously?', 'negative'),
# 			  ('I consider this theft.', 'negative'),
# 			  ('Eew... This location needs a complete overhaul.', 'negative'),
# 			  ('We recently witnessed her poor quality of management towards other guests as well.', 'negative'),
# 			  ('Waited and waited and waited.', 'negative'),
# 			  ('The pizza tasted old, super chewy in not a good way.', 'negative'),
# 			  ('I swung in to give them a try but was deeply disappointed.', 'negative'),
# 			  ('Boy was that sucker dry.', 'negative'),
# 			  ('Over rated.', 'negative'),
# 			  ('If you look for authentic Thai food, go else where.', 'negative'),
# 			  ('After I pulled up my car I waited for another 15 minutes before being acknowledged.', 'negative'),
# 			  ('I hate those things as much as cheap quality black olives.', 'negative'),
# 			  ('The kids play area is NASTY', 'negative'),
# 			  ('It was extremely "crumby" and pretty tasteless.', 'negative'),
# 			  ('It was a pale color instead of nice and char and has NO flavor.', 'negative'),
# 			  ('I got home to see the driest damn wings ever', 'negative'),
# 			  ('Not good for the money.', 'negative'),
# 			  ('I just wanted to leave.', 'negative'),
# 			  ('I will not be eating there again.', 'negative'),
# 			  ('....THE OWNERS REALLY REALLY need to quit being soooooo cheap let them wrap my freaking sandwich in two papers not one', 'negative'),
# 			  ('I checked out this place a couple years ago and was not impressed.', 'negative'),
# 			  ('The chicken I got was definitely reheated and was only ok, the wedges were cold and soggy.', 'negative'),
# 			  ('Sorry, I will not be getting food from here anytime soon :(', 'negative'),
# 			  ('My friend did not like his Bloody Mary.', 'negative'),
# 			  ('Despite how hard I rate businesses, its actually rare for me to give a 1 star.', 'negative'),
# 			  ('I will not return.', 'negative'),
# 			  ('I had the chicken Pho and it tasted very bland.', 'negative'),
# 			  ('Very disappointing 	', 'negative'),
# 			  ('Best of luck to the rude and non-customer service focused new management.', 'negative'),
# 			  ('Any grandmother can make a roasted chicken better than this one.', 'negative'),
# 			  ('I asked multiple times for the wine list and after some time of being ignored I went to the hostess and got one myself.', 'negative'),
# 			  ('Same evening, him and I are both drastically sick.', 'negative'),
# 			  ('Ordered burger rare came in well done.', 'negative'),
# 			  ('Tried to go here for lunch and it was a madhouse.', 'negative'),
# 			  ('After waiting an hour and being seated, I was not in the greatest of moods.', 'negative'),
# 			  ('Im not eating here', 'negative'),
# 			  ('Maybe if they werent cold they would have been somewhat edible.', 'negative'),
# 			  ('This place has a lot of promise but fails to deliver.', 'negative'),
# 			  ('Very bad Experience', 'negative'),
# 			  ('What a mistake.', 'negative'),
# 			  ('Food was average at best.', 'negative'),
# 			  ('We wont be going back anytime soon', 'negative'),
# 			  ('Very Very Disappointed ordered the $35 Big Bay Plater.', 'negative'),
# 			  ('Not much flavor to them, and very poorly constructed.', 'negative'),
# 			  ('The fried rice was dry as well.', 'negative'),
# 			  ('Google mediocre and I imagine Smashburger will pop up.', 'negative'),
# 			  ('dont go here.', 'negative'),
# 			  ('As a sushi lover avoid this place by all means.', 'negative'),
# 			  ('The plantains were the worst Ive ever tasted.', 'negative'),
# 			  ('Service was slow and not attentive.', 'negative'),
# 			  ('Your staff spends more time talking to themselves than me.', 'negative'),
# 			  ('Total brunch fail.', 'negative'),
# 			  ('I probably wont be back, to be honest.', 'negative'),
# 			  ('Went for lunch - service was slow.', 'negative'),
# 			  ('We had so much to say about the place before we walked in that he expected it to be amazing, but was quickly disappointed.', 'negative'),
# 			  ('I was mortified.', 'negative'),
# 			  ('Needless to say, we will never be back here again.', 'negative'),
# 			  ('Anyways, The food was definitely not filling at all, and for the price you pay you should expect more.', 'negative'),
# 			  ('The chips that came out were dripping with grease, and mostly not edible.', 'negative'),
# 			  ('I wasnt really impressed with Strip Steak.', 'negative'),
# 			  ('I work in the hospitality industry in Paradise Valley and have refrained from recommending Cibo any longer.', 'negative'),
# 			  ('Would not recommend to others.', 'negative'),
# 			  ('I mean really, how do you get so famous for your fish and chips when its so terrible?', 'negative'),
# 			  ('Not my thing.', 'negative'),
# 			  ('If you are reading this please dont go there.', 'negative'),
# 			  ('Tonight I had the Elk Filet special...and it sucked.', 'negative'),
# 			  ('A FLY was in my apple juice.. A FLY', 'negative'),
# 			  ('The food was barely lukewarm, so it must have been sitting waiting for the server to bring it out to us.', 'negative'),
# 			  ('Ryans Bar is definitely one Edinburgh establishment I wont be revisiting.', 'negative'),
# 			  ('Probably never coming back, and wouldnt recommend it.', 'negative'),
# 			  ('Friends pasta -- also bad, he barely touched it.', 'negative'),
# 			  ('It was way over fried.', 'negative'),
# 			  ('Im not sure how long we stood there but it was long enough for me to begin to feel awkwardly out of place.', 'negative'),
# 			  ('When I opened the sandwich, I was impressed, but not in a good way.', 'negative'),
# 			  ('Will not be back', 'negative'),
# 			  ('I have watched their prices inflate, portions get smaller and management attitudes grow rapidly', 'negative'),
# 			  ('Main thing I didnt enjoy is that the crowd is of older crowd, around mid 30s and up.', 'negative'),
# 			  ('I had to wait over 30 minutes to get my drink and longer to get 2 arepas.', 'negative'),
# 			  ('The service was poor and thats being nice.', 'negative'),
# 			  ('The place was not clean and the food oh so stale', 'negative'),
# 			  ('The chicken dishes are OK, the beef is like shoe leather.', 'negative'),
# 			  ('But the service was beyond bad.', 'negative'),
# 			  ('Tasted like dirt.', 'negative'),
# 			  ('My sashimi was poor quality being soggy and tasteless.', 'negative'),
# 			  ('the food is not tasty at all, not to say its "real traditional Hunan style".', 'negative'),
# 			  ('What did bother me, was the slow service.', 'negative'),
# 			  ('Their frozen margaritas are WAY too sugary for my taste.', 'negative'),
# 			  ('So in a nutshell: 1) The restaraunt smells like a combination of a dirty fish market and a sewer.', 'negative'),
# 			  ('My girlfriends veal was very bad.', 'negative'),
# 			  ('Unfortunately, it was not good.', 'negative'),
# 			  ('Bland and flavorless is a good way of describing the barely tepid meat.', 'negative'),
# 			  ('The chains, which Im no fan of, beat this place easily.', 'negative'),
# 			  ('We will not be coming back.', 'negative'),
# 			  ('Once your food arrives its meh.', 'negative'),
# 			  ('My brother in law who works at the mall ate here same day, and guess what he was sick all night too.', 'negative'),
# 			  ('Mediocre food.', 'negative'),
# 			  ('Im super pissd.', 'negative'),
# 			  ('Why are these sad little vegetables so overcooked?', 'negative'),
# 			  ('Not a single employee came out to see if we were OK or even needed a water refill once they finally served us our food.', 'negative'),
# 			  ('The server was very negligent of our needs and made us feel very unwelcome... I would not suggest this place', 'negative'),
# 			  ('The service was terrible though.', 'negative'),
# 			  ('This place is overpriced, not consistent with their boba, and it really is OVERPRICED', 'negative'),
# 			  ('It was packed', 'negative'),
# 			  ('The food was terrible.', 'negative'),
# 			  ('It kept getting worse and worse so now Im officially done.', 'negative'),
# 			  ('This place should honestly be blown up.', 'negative'),
# 			  ('But I definitely would not eat here again.', 'negative'),
# 			  ('Do not waste your money here', 'negative'),
# 			  ('Awful service.', 'negative'),
# 			  ('Wont ever go here again.', 'negative'),
# 			  ('Food quality has been horrible.', 'negative'),
# 			  ('For that price I can think of a few place I would have much rather gone.', 'negative'),
# 			  ('The service here is fair at best.', 'negative'),
# 			  ('I do love sushi, but I found Kabuki to be over-priced, over-hip and under-services.', 'negative'),
# 			  ('Do yourself a favor and stay away from this dish.', 'negative'),
# 			  ('Very poor service.', 'negative'),
# 			  ('No one at the table thought the food was above average or worth the wait that we had for it.', 'negative'),
# 			  ('I paid the bill but did not tip because I felt the server did a terrible job.', 'negative'),
# 			  ('Food is way overpriced and portions are fucking small.', 'negative'),
# 			  ('for 40 bucks a head, i really expect better food.', 'negative'),
# 			  ('I wont be back.', 'negative'),
# 			  ('We could not believe how dirty the oysters were', 'negative'),
# 			  ('This place deserves no stars.', 'negative'),
# 			  ('I would not recommend this place.', 'negative'),
# 			  ('To my disbelief, each dish qualified as the worst version of these foods I have ever tasted.', 'negative'),
# 			  ('I probably would not go here again.', 'negative'),
# 			  ('The Wife hated her meal (coconut shrimp), and our friends really did not enjoy their meals, either.', 'negative'),
# 			  ('My fella got the huevos rancheros and they didnt look too appealing.', 'negative'),
# 			  ('I probably wont be coming back here.', 'negative'),
# 			  ('Worst food/service Ive had in a while.', 'negative'),
# 			  ('The feel of the dining room was more college cooking course than high class dining and the service was slow at best.', 'negative'),
# 			  ('I started this review with two stars, but Im editing it to give it only one.', 'negative'),
# 			  ('this is the worst sushi i have ever eat besides Costcos.', 'negative'),
# 			  ('Weird vibe from owners.', 'negative'),
# 			  ('There was hardly any meat.', 'negative'),
# 			  ('Ive had better bagels from the grocery store.', 'negative'),
# 			  ('Now the burgers arent as good, the pizza which used to be amazing is doughy and flavorless.', 'negative'),
# 			  ('I found a six inch long piece of wire in my salsa.', 'negative'),
# 			  ('The service was terrible, food was mediocre.', 'negative'),
# 			  ('I ordered Albondigas soup - which was just warm - and tasted like tomato soup with frozen meatballs.', 'negative'),
# 			  ('I had about two bites and refused to eat anymore.', 'negative'),
# 			  ('The service was extremely slow.', 'negative'),
# 			  ('After 20 minutes wait, I got a table.', 'negative'),
# 			  ('No allergy warnings on the menu, and the waitress had absolutely no clue as to which meals did or did not contain peanuts.', 'negative'),
# 			  ('Pricing is a bit of a concern at Mellow Mushroom.', 'negative'),
# 			  ('Worst Thai ever.', 'negative'),
# 			  ('Highly unprofessional and rude to a loyal patron', 'negative'),
# 			  ('Spend your money elsewhere.', 'negative'),
# 			  ('The Buffet at Bellagio was far from what I anticipated.', 'negative'),
# 			  ('And the drinks are WEAK, people', 'negative'),
# 			  ('-My order was not correct.', 'negative'),
# 			  ('Also, I feel like the chips are bought, not made in house.', 'negative'),
# 			  ('After the disappointing dinner we went elsewhere for dessert.', 'negative'),
# 			  ('We wont be returning.', 'negative'),
# 			  ('Very, very sad.', 'negative'),
# 			  ('i felt insulted and disrespected, how could you talk and judge another human being like that?', 'negative'),
# 			  ('How can you call yourself a steakhouse if you cant properly cook a steak, I dont understand', 'negative'),
# 			  ('Im not impressed with the concept or the food.', 'negative'),
# 			  ('The only thing I wasnt too crazy about was their guacamole as I dont like it.', 'negative'),
# 			  ('There is really nothing for me at postinos, hope your experience is better', 'negative'),
# 			  ('I got food poisoning here at the buffet.', 'negative'),
# 			  ('They brought a fresh batch of fries and I was thinking yay something warm but no', 'negative'),
# 			  ('What SHOULD have been a hilarious, yummy Christmas Eve dinner to remember was the biggest fail of the entire trip for us.', 'negative'),
# 			  ('Needless to say, I wont be going back anytime soon.', 'negative'),
# 			  ('This place is disgusting', 'negative'),
# 			  ('The RI style calamari was a joke.', 'negative'),
# 			  ('However, there was so much garlic in the fondue, it was barely edible.', 'negative'),
# 			  ('I could barely stomach the meal, but didnt complain because it was a business lunch.', 'negative'),
# 			  ('It was so bad, I had lost the heart to finish it.', 'negative'),
# 			  ('It also took her forever to bring us the check when we asked for it.', 'negative'),
# 			  ('We arent ones to make a scene at restaurants but I just dont get it...definitely lost the love after this one', 'negative'),
# 			  ('Disappointing experience.', 'negative'),
# 			  ('The food is about on par with Dennys, which is to say, not good at all.', 'negative'),
# 			  ('If you want to wait for mediocre food and downright terrible service, then this is the place for you.', 'negative'),
# 			  ('WAAAAAAyyyyyyyyyy over rated is all I am saying.', 'negative'),
# 			  ('We wont be going back.', 'negative'),
# 			  ('The place was fairly clean but the food simply wasnt worth it.', 'negative'),
# 			  ('This place lacked style', 'negative'),
# 			  ('The sangria was about half of a glass wine full and was $12, ridiculous.', 'negative'),
# 			  ('Dont bother coming here.', 'negative'),
# 			  ('The meat was pretty dry, I had the sliced brisket and pulled pork.', 'negative'),
# 			  ('The building itself seems pretty neat; the bathroom is pretty trippy, but I wouldnt eat here again.', 'negative'),
# 			  ('It was equally awful.', 'negative'),
# 			  ('Probably not in a hurry to go back.', 'negative'),
# 			  ('very slow at seating even with reservation.', 'negative'),
# 			  ('Not good by any stretch of the imagination.', 'negative'),
# 			  ('The cashew cream sauce was bland and the vegetables were undercooked.', 'negative'),
# 			  ('The chipolte ranch dipping sause was tasteless, seemed thin and watered down with no heat.', 'negative'),
# 			  ('It was a bit too sweet, not really spicy enough, and lacked flavor.', 'negative'),
# 			  ('I was VERY disappointed', 'negative'),
# 			  ('This place is horrible and way overpriced.', 'negative'),
# 			  ('Maybe its just their Vegetarian fare, but Ive been twice and I thought it was average at best.', 'negative'),
# 			  ('It wasnt busy at all and now we know why.', 'negative'),
# 			  ('The tables outside are also dirty a lot of the time and the workers are not always friendly and helpful with the menu.', 'negative'),
# 			  ('The ambiance here did not feel like a buffet setting, but more of a douchey indoor garden for tea and biscuits.', 'negative'),
# 			  ('Con: spotty service.', 'negative'),
# 			  ('The fries were not hot, and neither was my burger.', 'negative'),
# 			  ('But then they came back cold.', 'negative'),
# 			  ('Then our food came out, disappointment ensued.', 'negative'),
# 			  ('The real disappointment was our waiter.', 'negative'),
# 			  ('My husband said she was very rude... did not even apologize for the bad food or anything.', 'negative'),
# 			  ('The only reason to eat here would be to fill up before a night of binge drinking just to get some carbs in your stomach.', 'negative'),
# 			  ('Insults, profound deuchebaggery, and had to go outside for a smoke break while serving just to solidify it.', 'negative'),
# 			  ('If someone orders two tacos dont you think it may be part of customer service to ask if it is combo or ala cart?', 'negative'),
# 			  ('She was quite disappointed although some blame needs to be placed at her door.', 'negative'),
# 			  ('After all the rave reviews I couldnt wait to eat here......what a disappointment', 'negative'),
# 			  ('Del Taco is pretty nasty and should be avoided if possible.', 'negative'),
# 			  ('Its NOT hard to make a decent hamburger.', 'negative'),
# 			  ('But I dont like it.', 'negative'),
# 			  ('Hell no will I go back', 'negative'),
# 			  ('Weve have gotten a much better service from the pizza place next door than the services we received from this restaurant.', 'negative'),
# 			  ('I dont know what the big deal is about this place, but I wont be back "yaall".', 'negative'),
# 			  ('The ambiance isnt much better.', 'negative'),
# 			  ('Unfortunately, it only set us up for disapppointment with our entrees.', 'negative'),
# 			  ('The food wasnt good.', 'negative'),
# 			  ('Your servers suck, wait, correction, our server Heimer sucked.', 'negative'),
# 			  ('What happened next was pretty....off putting.', 'negative'),
# 			  ('too bad cause I know its family owned, I really wanted to like this place.', 'negative'),
# 			  ('Overpriced for what you are getting.', 'negative'),
# 			  ('I vomited in the bathroom mid lunch.', 'negative'),
# 			  ('I kept looking at the time and it had soon become 35 minutes, yet still no food.', 'negative'),
# 			  ('I have been to very few places to eat that under no circumstances would I ever return to, and this tops the list.', 'negative'),
# 			  ('We started with the tuna sashimi which was brownish in color and obviously wasnt fresh.', 'negative'),
# 			  ('Food was below average.', 'negative'),
# 			  ('It sure does beat the nachos at the movies but I would expect a little bit more coming from a restaurant.', 'negative'),
# 			  ('All in all, Ha Long Bay was a bit of a flop.', 'negative'),
# 			  ('Shrimp- When I unwrapped it (I live only 1/2 a mile from Brushfire) it was literally ice cold.', 'negative'),
# 			  ('It lacked flavor, seemed undercooked, and dry.', 'negative'),
# 			  ('It really is impressive that the place hasnt closed down.', 'negative'),
# 			  ('I would avoid this place if you are staying in the Mirage.', 'negative'),
# 			  ('The refried beans that came with my meal were dried out and crusty and the food was bland.', 'negative'),
# 			  ('Spend your money and time some place else.', 'negative'),
# 			  ('A lady at the table next to us found a live green caterpillar In her salad.', 'negative'),
# 			  ('the presentation of the food was awful.', 'negative'),
# 			  ('I cant tell you how disappointed I was.', 'negative'),
# 			  ('I think food should have flavor and texture and both were lacking.', 'negative'),
# 			  ('Appetite instantly gone.', 'negative'),
# 			  ('Overall I was not impressed and would not go back.', 'negative'),
# 			  ('The whole experience was underwhelming, and I think well just go to Ninja Sushi next time.', 'negative')