pos_tweets = [('I love this car', 'positive'),
              ('This view is amazing', 'positive'),
              ('I feel great this morning', 'positive'),
              ('I am so excited about the concert', 'positive'),
              ('He is my best friend', 'positive'),
              ('Wow... Loved this place.', 'positive'),
              ('Stopped by during the late May bank holiday off Rick Steve recommendation and loved it.', 'positive'),
              ('The selection on the menu was great and so were the prices.', 'positive'),
              ('The fries were great too.', 'positive'),
              ('A great touch.', 'positive'),
              ('Service was very prompt.', 'positive'),
              ('I tried the Cape Cod ravoli, chicken,with cranberry...mmmm', 'positive'),
              ('Highly recommended.', 'positive'),
              ('The food, amazing.', 'positive'),
              ('Service is also cute.', 'positive'),
              ('I could care less... The interior is just beautiful.', 'positive'),
              ('So they performed.', 'positive'),
              ('Thats right....the red velvet cake.....ohhh this stuff is so good.', 'positive'),
              ('This hole in the wall has great Mexican street tacos, and friendly staff.', 'positive'),
              ('Also there are combos like a burger, fries, and beer for 23 which is a decent deal.', 'positive'),
              ('I found this place by accident and I could not be happier.', 'positive'),
              ('Overall, I like this place a lot.', 'positive'),
              ('The only redeeming quality of the restaurant was that it was very inexpensive.', 'positive'),
              ('Ample portions and good prices.', 'positive'),
              ('My first visit to Hiro was a delight', 'positive'),
              ('The shrimp tender and moist.', 'positive'),
              ('On a positive note, our server was very attentive and provided great service.', 'positive'),
              ('The only thing I did like was the prime rib and dessert section.', 'positive'),
              ('The burger is good beef, cooked just right.', 'positive'),
              ('If you want a sandwich just go to any Firehouse', 'positive'),
              ('My side Greek salad with the Greek dressing was so tasty, and the pita and hummus was very refreshing.', 'positive'),
              ('We ordered the duck rare and it was pink and tender on the inside with a nice char on the outside.', 'positive'),
              ('He came running after us when he realized my husband had left his sunglasses on the table.', 'positive'),
              ('Their chow mein is so good', 'positive'),
              ('The portion was huge', 'positive'),
              ('Loved it...friendly servers, great food, wonderful and imaginative menu.', 'positive'),
              ('The salad had just the right amount of sauce to not over power the scallop, which was perfectly cooked.', 'positive'),
              ('This place receives stars for their APPETIZERS', 'positive'),
              ('The cocktails are all handmade and delicious.', 'positive'),
              ('Wed definitely go back here again.', 'positive'),
              ('We are so glad we found this place.', 'positive'),
              ('Great food and service, huge portions and they give a military discount.', 'positive'),
              ('Always a great time at Dos Gringos', 'positive'),
              ('Update.....went back for a second time and it was still just as amazing', 'positive'),
              ('A great way to finish a great.', 'positive'),
              ('The deal included 5 tastings and 2 drinks, and Jeff went above and beyond what we expected.', 'positive'),
              ('- Really, really good rice, all the time.', 'positive'),
              ('The sweet potato fries were very good and seasoned well.', 'positive'),
              ('Today is the second time Ive been to their lunch buffet and it was pretty good.', 'positive'),
              ('This place has it', 'positive'),
              ('I love the Pho and the spring rolls oh so yummy you have to try.', 'positive'),
              ('All I have to say is the food was amazing', 'positive'),
              ('Omelets are to die for', 'positive'),
              ('Everything was fresh and delicious', 'positive'),
              ('Its like a really sexy party in your mouth, where youre outrageously flirting with the hottest person at the party.', 'positive'),
              ('Best breakfast buffet', 'positive'),
              ('Will be back again', 'positive'),
              ('Food arrived quickly', 'positive'),
              ('On the up side, their cafe serves really good food.', 'positive'),
              ('another marrow to go', 'positive'),
              ('The only good thing was our waiter, he was very helpful and kept the bloddy marys coming.', 'positive'),
              ('Best Buffet in town, for the price you cannot beat it.', 'positive'),
              ('I LOVED their mussels cooked in this wine reduction, the duck was tender, and their potato dishes were delicious.', 'positive'),
              ('This is one of the better buffets that I have been to.', 'positive'),
              ('So we went to Tigerlilly and had a fantastic afternoon', 'positive'),
              ('The food was delicious, our bartender was attentive and personable AND we got a great deal', 'positive'),
              ('The ambience is wonderful and there is music playing.', 'positive'),
              ('Will go back next trip out.', 'positive'),
              ('Sooooo good', 'positive'),
              ('This is a really fantastic Thai restaurant which is definitely worth a visit.', 'positive'),
              ('Nice, spicy and tender.', 'positive'),
              ('Good prices.', 'positive'),
              ('Check it out.', 'positive'),
              ('Service was fine and the waitress was friendly.', 'positive'),
              ('hes ever eaten.', 'positive'),
              ('We thought youd have to venture further away to get good sushi, but this place really hit the spot that night.', 'positive'),
              ('Phenomenal food, service and ambiance.', 'positive'),
              ('Definitely worth venturing off the strip for the pork belly, will return next time Im in Vegas.', 'positive'),
              ('Penne vodka excellent', 'positive'),
              ('tasty burgers.', 'positive'),
              ('Delicious NYC bagels, good selections of cream cheese, real Lox with capers even.', 'positive'),
              ('Great Subway, in fact its so good when you come here every other Subway will not meet your expectations.', 'positive'),
              ('I had a seriously solid breakfast here.', 'positive'),
              ('This is one of the best bars with food in Vegas.', 'positive'),
              ('My drink was never empty and he made some really great menu suggestions.', 'positive'),
              ('Nice blanket of moz over top but i feel like this was done to cover up the subpar food.', 'positive'),
              ('The bathrooms are clean and the place itself is well decorated.', 'positive'),
              ('My fianc and I came in the middle of the day and we were greeted and seated right away.', 'positive'),
              ('This is a great restaurant at the Mandalay Bay.', 'positive'),
              ('Some highlights : Great quality nigiri here', 'positive'),
              ('the staff is friendly and the joint is always clean.', 'positive'),
              ('this was a different cut than the piece the other day but still wonderful and tender s well as well flavored.', 'positive'),
              ('this place is good.', 'positive'),
              ('I was seated immediately.', 'positive'),
              ('Their menu is diverse, and reasonably priced.', 'positive'),
              ('Restaurant is always full but never a wait.', 'positive'),
              ('DELICIOUS', 'positive'),
              ('This place is hands-down one of the best places to eat in the Phoenix metro area.', 'positive'),
              ('Bacon is hella salty.', 'positive'),
              'This really is how Vegas fine dining used to be, right down to the menus handed to the ladies that have no prices listed.positive', ('positive'),
              ('The waitresses are very friendly.', 'positive'),
              ('Lordy, the Khao Soi is a dish that is not to be missed for curry lovers', 'positive'),
              ('daughter.', 'positive'),
              ('The atmosphere is modern and hip, while maintaining a touch of coziness.', 'positive'),
              ('Not a weekly haunt, but definitely a place to come back to every once in a while.', 'positive'),
              ('Love this place, hits the spot when I want something healthy but not lacking in quantity or flavor.', 'positive'),
              ('I ordered the Lemon raspberry ice cocktail which was also incredible.', 'positive'),
              ('Interesting decor.', 'positive'),
              ('What I really like there is the crepe station.', 'positive'),
              'Also were served hot bread and butter, and home made potato chips with bacon bits on top....very original and very good.', ('positive'),
              ('you can watch them preparing the delicious food)', 'positive'),
              ('Both of the egg rolls were fantastic.', 'positive'),
              ('I had a salad with the wings, and some ice cream for dessert and left feeling quite satisfied.', 'positive'),
              ('The best place to go for a tasty bowl of Pho', 'positive'),
              ('Very friendly staff.', 'positive'),
              ('It is worth the drive.', 'positive'),
              ('I had heard good things about this place, but it exceeding every hope I could have dreamed of.', 'positive'),
              ('Food was great and so was the serivce', 'positive'),
              ('Great brunch spot.', 'positive'),
              ('Service is friendly and inviting.', 'positive'),
              ('Very good lunch spot.', 'positive'),
              ('The sides are delish - mixed mushrooms, yukon gold puree, white corn - beateous.', 'positive'),
              ('My friend loved the salmon tartar.', 'positive'),
              ('Extremely Tasty', 'positive'),
              ('Waitress was good though', 'positive'),
              ('The Jamaican mojitos are delicious.', 'positive'),
              ('- the food is rich so order accordingly.', 'positive'),
              ('I loved the bacon wrapped dates.', 'positive'),
              ('This is an unbelievable BARGAIN', 'positive'),
              ('The folks at Otto always make us feel so welcome and special.', 'positive'),
              ('This is the place where I first had pho and it was amazing', 'positive'),
              ('This wonderful experience made this place a must-stop whenever we are in town again.', 'positive'),
              ('Very very fun chef.', 'positive'),
              ('Great place to have a couple drinks and watch any and all sporting events as the walls are covered with TVs.', 'positive'),
              'Id say that would be the hardest decision... Honestly, all of Ms dishes taste how they are supposed to taste (amazing).', ('positive'),
              ('Everyone is very attentive, providing excellent customer service.', 'positive'),
              ('Now this dish was quite flavourful.', 'positive'),
              ('Seriously flavorful delights, folks.', 'positive'),
              ('Much better than the other AYCE sushi place I went to in Vegas.', 'positive'),
              ('The lighting is just dark enough to set the mood.', 'positive'),
              ('Owners are really great people.', 'positive'),
              ('The Greek dressing was very creamy and flavorful.', 'positive'),
              ('Now the pizza itself was good the peanut sauce was very tasty.', 'positive'),
              ('We had 7 at our table and the service was pretty fast.', 'positive'),
              ('Fantastic service here.', 'positive'),
              ('They know how to make them here.', 'positive'),
              ('I hope this place sticks around.', 'positive'),
              ('The restaurant atmosphere was exquisite.', 'positive'),
              ('Good service, very clean, and inexpensive, to boot', 'positive'),
              ('The seafood was fresh and generous in portion.', 'positive'),
              ('Plus, its only 8 bucks.', 'positive'),
              ('Thus far, have only visited twice and the food was absolutely delicious each time.', 'positive'),
              ('Just as good as when I had it more than a year ago', 'positive'),
              ('The Veggitarian platter is out of this world', 'positive'),
              ('You cant go wrong with any of the food here.', 'positive'),
              ('You cant beat that.', 'positive'),
              ('Stopped by this place while in Madison for the Ironman, very friendly, kind staff.', 'positive'),
              ('The chefs were friendly and did a good job.', 'positive'),
              ('I liked the patio and the service was outstanding.', 'positive'),
              ('The goat taco didnt skimp on the meat and wow what FLAVOR', 'positive'),
              ('I went to Bachi Burger on a friends recommendation and was not disappointed.', 'positive'),
              ('I would definitely recommend the wings as well as the pizza.', 'positive'),
              ('Great Pizza and Salads', 'positive'),
              ('This place is amazing', 'positive'),
              ('The staff is great, the food is delish, and they have an incredible beer selection.', 'positive'),
              ('I didnt know pulled pork could be soooo delicious.', 'positive'),
              ('You get incredibly fresh fish, prepared with care.', 'positive'),
              ('I love the fact that everything on their menu is worth it.', 'positive'),
              ('The food was excellent and service was very good.', 'positive'),
              ('Good beer & drink selection and good food selection.', 'positive'),
              ('Good Service-check', 'positive'),
              ('In the summer, you can dine in a charming outdoor patio - so very delightful.', 'positive'),
              ('I did not expect this to be so good', 'positive'),
              ('Fantastic food', 'positive'),
              ('The food was very good.', 'positive'),
              ('Great food for the price, which is very high quality and house made.', 'positive'),
              ('Back to good BBQ, lighter fare, reasonable pricing and tell the public they are back to the old ways.', 'positive'),
              ('And considering the two of us left there very full and happy for about $20, you just cant go wrong.', 'positive'),
              ('All the bread is made in-house', 'positive'),
              ('Service was exceptional and food was a good as all the reviews.', 'positive'),
              ('A couple of months later, I returned and had an amazing meal.', 'positive'),
              ('Favorite place in town for shawarrrrrrma', 'positive'),
              ('The black eyed peas and sweet potatoes... UNREAL', 'positive'),
              ('You wont be disappointed.', 'positive'),
              ('They could serve it with just the vinaigrette and it may make for a better overall dish, but it was still very good.', 'positive'),
              ('Both of them were truly unbelievably good, and I am so glad we went back.', 'positive'),
              ('We had fantastic service, and were pleased by the atmosphere.', 'positive'),
              ('I love this place.', 'positive'),
              ('Great service and food.', 'positive'),
              ('OMG, the food was delicioso', 'positive'),
              ('Of all the dishes, the salmon was the best, but all were great.', 'positive'),
              ('The vegetables are so fresh and the sauce feels like authentic Thai.', 'positive'),
              ('Its worth driving up from Tucson', 'positive'),
              ('Pretty good beer selection too.', 'positive'),
              ('This place is like Chipotle, but BETTER.', 'positive'),
              ('Classy/warm atmosphere, fun and fresh appetizers, succulent steaks (Baseball steak', 'positive'),
              ('5 stars for the brick oven bread app', 'positive'),
              ('I have eaten here multiple times, and each time the food was delicious.', 'positive'),
              ('Everyone is treated equally special.', 'positive'),
              ('It was delicious', 'positive'),
              ('On the good side, the staff was genuinely pleasant and enthusiastic - a real treat.', 'positive'),
              ('As always the evening was wonderful and the food delicious', 'positive'),
              ('Best fish Ive ever had in my life', 'positive'),
              ('(The bathroom is just next door and very nice.)', 'positive'),
              ('This is an Outstanding little restaurant with some of the Best Food I have ever tasted.', 'positive'),
              ('Pretty cool I would say.', 'positive'),
              ('Server did a great job handling our large rowdy table.', 'positive'),
              ('Would come back again if I had a sushi craving while in Vegas.', 'positive'),
              ('The staff are great, the ambiance is great.', 'positive'),
              ('He deserves 5 stars.', 'positive'),
              ('The dining space is tiny, but elegantly decorated and comfortable.', 'positive'),
              ('They will customize your order any way youd like, my usual is Eggplant with Green Bean stir fry, love it', 'positive'),
              ('Best tacos in town by far', 'positive'),
              ('In an interesting part of town, this place is amazing.', 'positive'),
              ('They have great dinners.', 'positive'),
              ('The service was outshining & I definitely recommend the Halibut.', 'positive'),
              ('I will come back here every time Im in Vegas.', 'positive'),
              ('Def coming back to bowl next time', 'positive'),
              ('If you want healthy authentic or ethic food, try this place.', 'positive'),
              ('I have been here several times in the past, and the experience has always been great.', 'positive'),
              ('We walked away stuffed and happy about our first Vegas buffet experience.', 'positive'),
              ('mall by Aria.', 'positive'),
              ('pneumatic condiment dispenser.', 'positive'),
              ('Kids pizza is always a hit too with lots of great side dish options for the kiddos', 'positive'),
              ('Service is perfect and the family atmosphere is nice to see.', 'positive'),
              ('Cooked to perfection and the service was impeccable.', 'positive'),
              ('Great place to eat, reminds me of the little mom and pop shops in the San Francisco Bay Area.', 'positive'),
              ('Today was my first taste of a Buldogis Gourmet Hot Dog and I have to tell you it was more than I ever thought possible.positive', 'positive'),
              ('Ill definitely be in soon again.', 'positive'),
              ('Food was really good and I got full petty fast.', 'positive'),
              ('Service was fantastic.', 'positive'),
              ('I dont know what kind it is but they have the best iced tea.', 'positive'),
              ('Come hungry, leave happy and stuffed', 'positive'),
              ('I can assure you that you wont be disappointed.', 'positive'),
              ('I really enjoyed eating here.', 'positive'),
              ('First time going but I think I will quickly become a regular.', 'positive'),
              ('friendly until the end.', 'positive'),
              ('From what my dinner companions told me...everything was very fresh with nice texture and taste.', 'positive'),
              ('No complaints', 'positive'),
              ('This is some seriously good pizza and Im an expert/connisseur on the topic.', 'positive'),
              ('These are the nicest restaurant owners Ive ever come across.', 'positive'),
              ('We loved the biscuits', 'positive'),
              ('Service is quick and friendly.', 'positive'),
              ('So absolutley fantastic.', 'positive'),
              ('definitely will come back here again.', 'positive'),
              ('I like Steiners because its dark and it feels like a bar.', 'positive'),
              ('Wow very spicy but delicious.', 'positive'),
              ('If youre not familiar, check it out.', 'positive'),
              ('Id love to go back.', 'positive'),
              ('Anyway, this FS restaurant has a wonderful breakfast/lunch.', 'positive'),
              ('Each day of the week they have a different deal and its all so delicious', 'positive'),
              ('Not to mention the combination of pears, almonds and bacon is a big winner', 'positive'),
              ('The food is delicious and just spicy enough, so be sure to ask for spicier if you prefer it that way.', 'positive'),
              ('My ribeye steak was cooked perfectly and had great mesquite flavor.', 'positive'),
              ('Food was so gooodd.', 'positive'),
              ('The food was very good and I enjoyed every mouthful, an enjoyable relaxed venue for couples small family groups etc.', 'positive'),
              ('Nargile - I think you are great.', 'positive'),
              ('Best tater tots in the southwest.', 'positive'),
              ('We loved the place.', 'positive'),
              ('The vanilla ice cream was creamy and smooth while the profiterole (choux) pastry was fresh enough.', 'positive'),
              ('Im in AZ all the time and now have my new spot.', 'positive'),
              ('The inside is really quite nice and very clean.', 'positive'),
              ('The food was outstanding and the prices were very reasonable.', 'positive'),
              ('Love the margaritas, too', 'positive'),
              ('This was my first and only Vegas buffet and it did not disappoint.', 'positive'),
              ('Very good, though', 'positive'),
              ('Great pork sandwich.', 'positive'),
              ('We enjoy their pizza and brunch.', 'positive'),
              ('The steaks are all well trimmed and also perfectly cooked.', 'positive'),
              ('We had a group of 70+ when we claimed we would only have 40 and they handled us beautifully.', 'positive'),
              ('I LOVED it', 'positive'),
              ('This place is a jewel in Las Vegas, and exactly what Ive been hoping to find in nearly ten years living here.', 'positive'),
              ('Delicious and I will absolutely be back', 'positive'),
              ('This isnt a small family restaurant, this is a fine dining establishment.', 'positive'),
              ('They had a toro tartare with a cavier that was extraordinary and I liked the thinly sliced wagyu with white truffle.', 'positive'),
              ('How awesome is that.', 'positve'),
              ('I will be back many times soon.', 'positive'),
              ('The menu had so much good stuff on it i could not decide', 'positive'),
              ('CONCLUSION: Very filling meals.', 'positive'),
              ('Their daily specials are always a hit with my group.', 'positive'),
              ('The pancake was also really good and pretty large at that.', 'positive'),
              ('This was my first crawfish experience, and it was delicious', 'positive'),
              ('Their monster chicken fried steak and eggs is my all time favorite.', 'positive'),
              ('Waitress was sweet and funny.', 'positive'),
              ('I also had to taste my Moms multi-grain pumpkin pancakes with pecan butter and they were amazing, fluffy, and delicious', 'positive'),
              ('Cant say enough good things about this place.', 'positive'),
              ('The ambiance was incredible.', 'positive'),
              ('The waitress and manager are so friendly.', 'positive'),
              ('I dont each much pasta, but I love the homemade /hand made pastas and thin pizzas here.', 'positive'),
              ('Give it a try, you will be happy you did.', 'positive'),
              ('By far the BEST cheesecurds we have ever had', 'positive'),
              ('Reasonably priced also', 'positive'),
              ('Everything was perfect the night we were in.', 'positive'),
              ('The food is very good for your typical bar food.', 'positive'),
              ('At first glance it is a lovely bakery cafe - nice ambiance, clean, friendly staff.', 'positive'),
              ('Point your finger at any item on the menu, order it and you wont be disappointed.', 'positive'),
              ('Oh this is such a thing of beauty, this restaurant.', 'positive'),
              ('If you havent gone here GO NOW', 'positive'),
              ('Those burgers were amazing.', 'positive'),
              ('Be sure to order dessert, even if you need to pack it to-go - the tiramisu and cannoli are both to die for.', 'positive'),
              ('This was my first time and I cant wait until the next.', 'positive'),
              ('The bartender was also nice.', 'positive'),
              ('Everything was good and tasty', 'positive'),
              ('This place is two thumbs up....way up.', 'positive'),
              ('The best place in Vegas for breakfast (just check out a Sat, or Sun.', 'positive'),
              ('this place.', 'positive'),
              ('An excellent new restaurant by an experienced Frenchman.', 'positive'),
              ('Great steak, great sides, great wine, amazing desserts.', 'positive'),
              ('The steak and the shrimp are in my opinion the best entrees at GC.', 'positive'),
              ('I had the opportunity today to sample your amazing pizzas', 'positive'),
              ('The yellowtail carpaccio was melt in your mouth fresh.', 'positive'),
              ('Just spicy enough.. Perfect actually.', 'positive'),
              ('Last night was my second time dining here and I was so happy I decided to go back', 'positive'),
              ('quality of food and service.', 'positive'),
              ('I really do recommend this place, you can go wrong with this donut place', 'positive'),
              ('Nice ambiance.', 'positive'),
              ('I would recommend saving room for this', 'positive'),
              ('All of the tapas dishes were delicious', 'positive'),
              ('I *heart* this place.', 'positive'),
              ('A good time', 'positive'),
              ('I believe that this place is a great stop for those with a huge belly and hankering for sushi.', 'positive'),
              ('Generous portions and great taste.', 'positive'),
              ('Food was delicious', 'positive'),
              ('He also came back to check on us regularly, excellent service.', 'positive'),
              ('Our server was super nice and checked on us many times.', 'positive'),
              ('Service was good and the company was better', 'positive'),
              ('The staff are also very friendly and efficient.', 'positive'),
              ('As for the service: Im a fan, because its quick and youre being served by some nice folks.', 'positive'),
              ('Their steaks are 100% recommended', 'positive'),
              ('Great food and great service in a clean and friendly setting.', 'positive'),
              ('All in all, I can assure you Ill be back.', 'positive'),
              ('Great place fo take out or eat in.', 'positive'),
              ('The waitress was friendly and happy to accomodate for vegan/veggie options.', 'positive'),
              ('OMG I felt like I had never eaten Thai food until this dish.', 'positive'),
              ('The croutons also taste homemade which is an extra plus.', 'positive'),
              ('Itll be a regular stop on my trips to Phoenix', 'positive'),
              ('I really enjoyed Crema Caf before they expanded; I even told friends they had the BEST breakfast.', 'positive'),
              ('I miss it and wish they had one in Philadelphia', 'positive'),
              ('They also have the best cheese crisp in town.', 'positive'),
              ('Good value, great food, great service.', 'positive'),
              ('Couldnt ask for a more satisfying meal.', 'positive'),
              ('The food is good.', 'positive'),
              ('It was awesome.', 'positive'),
              ('We made the drive all the way from North Scottsdale... and I was not one bit disappointed', 'positive'),
              ('An absolute must visit', 'positive'),
              ('The cow tongue and cheek tacos are amazing.', 'positive'),
              ('They really want to make your experience a good one.', 'positive'),
              ('The grilled chicken was so tender and yellow from the saffron seasoning.', 'positive'),
              ('Pretty awesome place.', 'positive'),
              ('Ambience is perfect.', 'positive'),
              ('The staff is always super friendly and helpful, which is especially cool when you bring two small boys and a baby', 'positive'),
              ('Four stars for the food & the guy in the blue shirt for his great vibe & still letting us in to eat ', 'positive'),
              ('The roast beef sandwich tasted really good', 'positive'),
              ('High-quality chicken on the chicken Caesar salad.', 'positive'),
              ('We were promptly greeted and seated.', 'positive'),
              ('impeccable.', 'positive'),
              ('This is a good joint.', 'positive'),
              ('The Macarons here are insanely good.', 'positive'),
              ('Our waiter was very attentive, friendly, and informative.', 'positive'),
              ('Great food.', 'positive'),
              ('Great place to relax and have an awesome burger and beer.', 'positive'),
              ('It is PERFECT for a sit-down family meal or get together with a few friends.', 'positive'),
              ('The patio seating was very comfortable.', 'positive'),
              ('Hands down my favorite Italian restaurant', 'positive'),
              ('That just SCREAMS "LEGIT" in my book...somethats also pretty rare here in Vegas.', 'positive'),
              ('It was just not a fun experience.', 'positive'),
              ('The atmosphere was great with a lovely duo of violinists playing songs we requested.', 'positive'),
              ('I personally love the hummus, pita, baklava, falafels and Baba Ganoush (its amazing what they do with eggplant).', 'positive'),
              ('Very convenient, since we were staying at the MGM', 'positive'),
              ('The owners are super friendly and the staff is courteous.', 'positive'),
              ('Both great', 'positive'),
              ('Eclectic selection.', 'positive'),
              ('The sweet potato tots were good but the onion rings were perfection or as close as I have had.', 'positive'),
              ('The staff was very attentive.', 'positive'),
              ('And the chef was generous with his time (even came around twice so we can take pictures with him).', 'positive'),
              ('The owner used to work at Nobu, so this place is really similar for half the price.', 'positive'),
              ('I promise they wont disappoint.', 'positive'),
              ('What a great double cheeseburger', 'positive'),
              ('Awesome service and food.', 'positive'),
              ('A fantastic neighborhood gem ', 'positive'),
              ('I cant wait to go back.', 'positive'),
              ('Its a great place and I highly recommend it.', 'positive'),
              ('I gave it 5 stars then, and Im giving it 5 stars now.', 'positive'),
              ('Dessert: Panna Cotta was amazing.', 'positive'),
              ('Very good food, great atmosphere.1', 'positive'),
              ('Damn good steak.', 'positive'),
              ('Prices are very reasonable, flavors are spot on, the sauce is home made, and the slaw is not drenched in mayo.', 'positive'),
              ('The decor is nice, and the piano music soundtrack is pleasant.', 'positive'),
              ('The steak was amazing...rge fillet relleno was the best seafood plate i have ever had', 'positive'),
              ('Good food , good service .', 'positive'),
              ('It was absolutely amazing.', 'positive'),
              ('will definitely be back', 'positive'),
              ('The sergeant pepper beef sandwich with auju sauce is an excellent sandwich as well.', 'positive'),
              ('Hawaiian Breeze, Mango Magic, and Pineapple Delight are the smoothies that Ive tried so far and theyre all good.', 'positive'),
              ('Have been going since 2007 and every meal has been awesome', 'positive'),
              ('Our server was very nice and attentive as were the other serving staff.', 'positive'),
              ('The cashier was friendly and even brought the food out to me.', 'positive'),
              ('The atmosphere here is fun.', 'positive'),
              ('Service is quick and even "to go" orders are just like we like it', 'positive'),
              ('That said, our mouths and bellies were still quite pleased.', 'positive'),
              ('2 Thumbs Up', 'positive'),
              ('I loved the grilled pizza, reminded me of legit Italian pizza.', 'positive'),
              ('Only Pros : Large seating area/ Nice bar area/ Great simple drink menu/ The BEST brick oven pizza with homemade dough', 'positive'),
              ('They have a really nice atmosphere.', 'positive'),
              ('After one bite, I was hooked.', 'positive'),
              ('Cute, quaint, simple, honest.', 'positive'),
              ('The chicken was deliciously seasoned and had the perfect fry on the outside and moist chicken on the inside.', 'positive'),
              ('The food was great as always, compliments to the chef.', 'positive'),
              ('Special thanks to Dylan T. for the recommendation on what to order :) All yummy for my tummy.', 'positive'),
              ('Awesome selection of beer.', 'positive'),
              ('Great food and awesome service', 'positive'),
              ('tip than that.', 'positive'),
              ('The Han Nan Chicken was also very tasty.', 'positive'),
              ('As for the service, I thought it was good.', 'positive'),
              ('Nicest Chinese restaurant Ive been in a while.', 'positive'),
              ('Overall, I like there food and the service.', 'positive'),
              ('They also now serve Indian naan bread with hummus and some spicy pine nut sauce that was out of this world.', 'positive'),
              ('Try them in the airport to experience some tasty food and speedy, friendly service.', 'positive'),
              ('I love the decor with the Chinese calligraphy wall paper.', 'positive'),
              ('Never had anything to complain about here.', 'positive'),
              ('The restaurant is very clean and has a family restaurant feel to it.', 'positive'),
              ('There was a warm feeling with the service and I felt like their guest for a special treat.', 'positive'),
              ('An extensive menu provides lots of options for breakfast.', 'positive'),
              ('I always order from the vegetarian menu during dinner, which has a wide array of options to choose from.', 'positive'),
              ('Wonderful lil tapas and the ambience made me feel all warm and fuzzy inside.', 'positive'),
              ('I got to enjoy the seafood salad, with a fabulous vinegrette.', 'positive'),
              ('The wontons were thin, not thick and chewy, almost melt in your mouth.', 'positive'),
              ('Level 5 spicy was perfect, where spice didnt over-whelm the soup.', 'positive'),
              ('We were sat right on time and our server from the get go was FANTASTIC', 'positive'),
              ('When Im on this side of town, this will definitely be a spot Ill hit up again', 'positive'),
              ('This is a GREAT place to eat', 'positive'),
              ('The jalapeno bacon is soooo good.', 'positive'),
              ('Food was good, service was good, Prices were good.', 'positive'),
              ('Im so happy to be here"', 'positive'),
              ('One of the few places in Phoenix that I would definately go back to again .', 'positive'),
              ('The block was amazing.', 'positive'),
              ('Its close to my house, its low-key, non-fancy, affordable prices, good food.', 'positive'),
              ('* Both the Hot & Sour & the Egg Flower Soups were absolutely 5 Stars', 'positive'),
              ('Great time - family dinner on a Sunday night.', 'positive'),
              ('The flair bartenders are absolutely amazing', 'positive'),
              ('These were so good we ordered them twice.', 'positive'),
              ('I had a pretty satifying experience.', 'positive'),
              ('Join the club and get awesome offers via email.', 'positive'),
              ('Perfect for someone (me) who only likes beer ice cold, or in this case, even colder.', 'positive'),
              ('The nachos are a MUST HAVE', 'positive'),
              ('I dont have very many words to say about this place, but it does everything pretty well.', 'positive'),
              ('The staff is super nice and very quick even with the crazy crowds of the downtown juries, lawyers, and court staff.', 'positive'),
              ('Great atmosphere, friendly and fast service.', 'positive'),
              ('When I received my Pita it was huge it did have a lot of meat in it so thumbs up there.', 'positive'),
              ('The classic Maine Lobster Roll was fantastic.', 'positive'),
              ('held here last night.', 'positive'),
              ('The chips and salsa were really good, the salsa was very fresh.', 'positive'),
              ('This place is great', 'positive'),
              ('Once you get inside youll be impressed with the place.', 'positive'),
              ('And service was super friendly.', 'positive'),
              ('This place was such a nice surprise', 'positive'),
              ('They were golden-crispy and delicious.', 'positive'),
              ('I could eat their bruschetta all day it is devine.', 'positive'),
              ('Lastly, the mozzarella sticks, they were the best thing we ordered.', 'positive'),
              ('The first time I ever came here I had an amazing experience, I still tell people how awesome the duck was.', 'positive'),
              ('I love this place.', 'positive'),
              ('I can say that the desserts were yummy.', 'positive'),
              ('The seasonal fruit was fresh white peach puree.', 'positive'),
              ('I love that they put their food in nice plastic containers as opposed to cramming it in little paper takeout boxes.', 'positive'),
              ('The crepe was delicate and thin and moist.', 'positive'),
              ('Best service and food ever, Maria our server was so good and friendly she made our day.', 'positive'),
              ('They were excellent.', 'positive'),
              ('Just had lunch here and had a great experience.', 'positive'),
              ('I recently tried Caballeros and I have been back every week since', 'positive'),
              ('The food came out at a good pace.', 'positive'),
              ('I ate there twice on my last visit, and especially enjoyed the salmon salad.', 'positive'),
              ('In fact Im going to round up to 4 stars, just because she was so awesome.', 'positive'),
              ('the potatoes were great and so was the biscuit.', 'positive'),
              ('So flavorful and has just the perfect amount of heat.', 'positive'),
              ('The price is reasonable and the service is great.', 'positive'),
              ('Went in for happy hour, great list of wines.', 'positive'),
              ('Some may say this buffet is pricey but I think you get what you pay for and this place you are getting quite a lot', 'positive'),
              ('This place is pretty good, nice little vibe in the restaurant.', 'positive'),
              ('Talk about great customer service of course we will be back.', 'positive'),
              ('I love their fries and their beans.', 'positive'),
              ('Always a pleasure dealing with him.', 'positive'),
              ('They have a plethora of salads and sandwiches, and everything Ive tried gets my seal of approval.', 'positive'),
              ('This place is awesome if you want something light and healthy during the summer.', 'positive'),
              ('For sushi on the Strip, this is the place to go.', 'positive'),
              ('The service was great, even the manager came and helped with our table.', 'positive'),
              ('All in all an excellent restaurant highlighted by great service, a unique menu, and a beautiful setting.', 'positive'),
              ('My boyfriend and i sat at the bar and had a completely delightful experience.', 'positive'),
              ('Go To Place for Gyros.', 'positive'),
              ('I love the owner/chef, his one authentic Japanese cool dude', 'positive'),
              ('We definately enjoyed ourselves.', 'positive'),
              ('Seriously killer hot chai latte.', 'positive'),
              ('My boyfriend tried the Mediterranean Chicken Salad and fell in love.', 'positive'),
              ('Their rotating beers on tap is also a highlight of this place.', 'positive'),
              ('If you stay in Vegas you must get breakfast here at least once.', 'positive'),
              ('I want to first say our server was great and we had perfect service.', 'positive'),
              ('The pizza selections are good.', 'positive'),
              ('I had strawberry tea, which was good.', 'positive'),
              ('Overall, a great experience.', 'positive'),
              ('Their regular toasted bread was equally satisfying with the occasional pats of butter... Mmmm...', 'positive'),
              ('The chips and sals a here is amazing', 'positive'),
              ('This is my new fav Vegas buffet spot.', 'positive'),
              ('Every time I eat here, I see caring teamwork to a professional degree.', 'positive')]